---
sudo: false
language: go
install:
  - sudo apt-get update
  - sudo apt-get install at # for testing upstart
  - mkdir ~/go
  - GOPATH=~/go go get -d -v ./... && go build -v ./...
go:
  - 1.4
script: sudo GOPATH=~/go PATH=$PATH `which go` test -v ./...
